### ISSUE TITLE
err

### ISSUE THREAD

**Issue by trampover** [yutent/sonist#4]
npm i && npm start
npm WARN sonist@0.1.0 No repository field.

up to date in 1.823s

> sonist@0.1.0 start /home/windboy/桌面/sonist-master
> electron .

/home/windboy/桌面/sonist-master/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/home/windboy/桌面/sonist-master/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/home/windboy/桌面/sonist-master/node_modules/electron/index.js:18:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/windboy/桌面/sonist-master/node_modules/electron/cli.js:3:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sonist@0.1.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sonist@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.8.0 → 6.5.0    │
   │       Run npm i npm to update       │
   │                                     │
   ╰─────────────────────────────────────╯

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/windboy/.npm/_logs/2019-01-16T10_19_08_221Z-debug.log

**Comment by yutent** [comment]
Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
